### ISSUE TITLE
[apm-ui] Tests are broken since a recent change in the Kibana apm-ui layout

### ISSUE THREAD

**Issue by v1v** [elastic/apm-integration-testing#770]
```
mv: cannot stat './kibana/x-pack/legacy/plugins/apm/typings/es_schemas': No such file or directory
Done in 25.13s.
yarn run v1.15.2
$ tsc ./tmp/apm-server-docs/*.ts --noEmit
tmp/apm-server-docs/ErrorRawDocs.ts(1,26): error TS2307: Cannot find module '../apm-ui-interfaces/raw/ErrorRaw'.
tmp/apm-server-docs/SpanRawDocs.ts(1,25): error TS2307: Cannot find module '../apm-ui-interfaces/raw/SpanRaw'
tmp/apm-server-docs/TransactionRawDocs.ts(1,32): error TS2307: Cannot find module '../apm-ui-interfaces/raw/TransactionRaw'.
error Command failed with exit code 1.
```

See build errors [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-downstream/detail/master/4200/pipeline#step-81-log-18)

![image](https://user-images.githubusercontent.com/2871786/75034134-7014c300-54a4-11ea-83d9-c0a1b71230d3.png)

Caused by https://github.com/elastic/kibana/pull/57532
